ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    #d.image = "ubuntu"
    d.build_dir = "."
    d.ports = ["80:3000"]
    
  end
  config.vm.synced_folder ".", "/vagrant"
end